"""initial tables

Revision ID: cba73a509ebc

Revises:

Create Date: 2026-02-24 16:23:14.721598

"""

from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa

revision: str = 'cba73a509ebc'

down_revision: Union[str, None] = None

branch_labels: Union[str, Sequence[str], None] = None

depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('users',

    sa.Column('id', sa.Uuid(), nullable=False),

    sa.Column('username', sa.String(length=50), nullable=False),

    sa.Column('email', sa.String(length=255), nullable=False),

    sa.Column('password_hash', sa.String(length=255), nullable=False),

    sa.Column('is_active', sa.Boolean(), nullable=False),

    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),

    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),

    sa.PrimaryKeyConstraint('id')

    )

    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_table('categories',

    sa.Column('id', sa.Uuid(), nullable=False),

    sa.Column('user_id', sa.UUID(), nullable=False),

    sa.Column('name', sa.String(length=100), nullable=False),

    sa.Column('color', sa.String(length=7), nullable=False),

    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),

    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),

    sa.PrimaryKeyConstraint('id')

    )

    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)

    op.create_table('notes',

    sa.Column('id', sa.Uuid(), nullable=False),

    sa.Column('user_id', sa.UUID(), nullable=False),

    sa.Column('category_id', sa.UUID(), nullable=True),

    sa.Column('title', sa.String(length=255), nullable=False),

    sa.Column('content', sa.Text(), nullable=False),

    sa.Column('language', sa.String(length=10), nullable=False),

    sa.Column('is_pinned', sa.Boolean(), nullable=False),

    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),

    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),

    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),

    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),

    sa.PrimaryKeyConstraint('id')

    )

    op.create_index(op.f('ix_notes_category_id'), 'notes', ['category_id'], unique=False)

    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)

    op.create_table('recordings',

    sa.Column('id', sa.Uuid(), nullable=False),

    sa.Column('note_id', sa.UUID(), nullable=False),

    sa.Column('file_path', sa.String(length=500), nullable=False),

    sa.Column('duration_seconds', sa.Float(), nullable=True),

    sa.Column('transcription', sa.Text(), nullable=False),

    sa.Column('confidence', sa.Float(), nullable=True),

    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),

    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),

    sa.PrimaryKeyConstraint('id')

    )

    op.create_index(op.f('ix_recordings_note_id'), 'recordings', ['note_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_recordings_note_id'), table_name='recordings')

    op.drop_table('recordings')

    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')

    op.drop_index(op.f('ix_notes_category_id'), table_name='notes')

    op.drop_table('notes')

    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')

    op.drop_table('categories')

    op.drop_index(op.f('ix_users_username'), table_name='users')

    op.drop_index(op.f('ix_users_email'), table_name='users')

    op.drop_table('users')

    # ### end Alembic commands ###